services:
  postgres:
    image: postgres:16-alpine
    container_name: medbooking-db
    environment:
      POSTGRES_DB: medbooking
      POSTGRES_USER: medbooking
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: